apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefox
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefox
  template:
    metadata:
      labels:
        app: kubefox
    spec:
      containers:
      - name: kubefox
        image: wzj751127122/kubefox:build-12
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubefox
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: kubefox